POST http://localhost:8080/token

{
	"username": "admin",
	"password": "password"
}

DELETE http://localhost:8080/authors/8

GET http://localhost:8080/authors

POST http://localhost:8080/authors

{
	"Name": "Gilles Deleuze",
	"Bio": "Bomb ass writer"
}

POST http://localhost:8080/books

{
	"title": "anti-oedipus",
	"description": "a nice book",
	"authorId": 1,
	"yearPublished": 2022,
	"copiesAvailable": 5,
	"copiesTotal": 5
}

GET http://localhost:8080/books

GET http://localhost:8080/books/1

PUT http://localhost:8080/books/1

{
	"Title": "anti-oedipuss",
	"Description": "a veeery nice book*",
	"AuthorID": 1
}

PATCH http://localhost:8080/books/1

{
	"Description": "a bad book*"
}

DELETE http://localhost:8080/books/1
